/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
export type WrapperWithdrawParams = {
  amountAtoms: beet.bignum;
};

/**
 * @category userTypes
 * @category generated
 */
export const wrapperWithdrawParamsBeet =
  new beet.BeetArgsStruct<WrapperWithdrawParams>(
    [['amountAtoms', beet.u64]],
    'WrapperWithdrawParams',
  );
