/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';
import * as beetSolana from '@metaplex-foundation/beet-solana';
export type GlobalFixed = {
  discriminant: beet.bignum;
  mint: web3.PublicKey;
  vault: web3.PublicKey;
  globalTradersRootIndex: number;
  globalDepositsRootIndex: number;
  globalDepositsMaxIndex: number;
  freeListHeadIndex: number;
  numBytesAllocated: number;
  vaultBump: number;
  globalBump: number;
  numSeatsClaimed: number;
};

/**
 * @category userTypes
 * @category generated
 */
export const globalFixedBeet = new beet.BeetArgsStruct<GlobalFixed>(
  [
    ['discriminant', beet.u64],
    ['mint', beetSolana.publicKey],
    ['vault', beetSolana.publicKey],
    ['globalTradersRootIndex', beet.u32],
    ['globalDepositsRootIndex', beet.u32],
    ['globalDepositsMaxIndex', beet.u32],
    ['freeListHeadIndex', beet.u32],
    ['numBytesAllocated', beet.u32],
    ['vaultBump', beet.u8],
    ['globalBump', beet.u8],
    ['numSeatsClaimed', beet.u16],
  ],
  'GlobalFixed',
);
