/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
export type GlobalCleanParams = {
  orderIndex: number;
};

/**
 * @category userTypes
 * @category generated
 */
export const globalCleanParamsBeet = new beet.BeetArgsStruct<GlobalCleanParams>(
  [['orderIndex', beet.u32]],
  'GlobalCleanParams',
);
