/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js';
import * as beetSolana from '@metaplex-foundation/beet-solana';
import * as beet from '@metaplex-foundation/beet';

/**
 * Arguments used to create {@link CreateMarketLog}
 * @category Accounts
 * @category generated
 */
export type CreateMarketLogArgs = {
  market: web3.PublicKey;
  creator: web3.PublicKey;
  baseMint: web3.PublicKey;
  quoteMint: web3.PublicKey;
};
/**
 * Holds the data for the {@link CreateMarketLog} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class CreateMarketLog implements CreateMarketLogArgs {
  private constructor(
    readonly market: web3.PublicKey,
    readonly creator: web3.PublicKey,
    readonly baseMint: web3.PublicKey,
    readonly quoteMint: web3.PublicKey,
  ) {}

  /**
   * Creates a {@link CreateMarketLog} instance from the provided args.
   */
  static fromArgs(args: CreateMarketLogArgs) {
    return new CreateMarketLog(
      args.market,
      args.creator,
      args.baseMint,
      args.quoteMint,
    );
  }

  /**
   * Deserializes the {@link CreateMarketLog} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [CreateMarketLog, number] {
    return CreateMarketLog.deserialize(accountInfo.data, offset);
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link CreateMarketLog} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<CreateMarketLog> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    );
    if (accountInfo == null) {
      throw new Error(`Unable to find CreateMarketLog account at ${address}`);
    }
    return CreateMarketLog.fromAccountInfo(accountInfo, 0)[0];
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, createMarketLogBeet);
  }

  /**
   * Deserializes the {@link CreateMarketLog} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [CreateMarketLog, number] {
    return createMarketLogBeet.deserialize(buf, offset);
  }

  /**
   * Serializes the {@link CreateMarketLog} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return createMarketLogBeet.serialize(this);
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link CreateMarketLog}
   */
  static get byteSize() {
    return createMarketLogBeet.byteSize;
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link CreateMarketLog} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      CreateMarketLog.byteSize,
      commitment,
    );
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link CreateMarketLog} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === CreateMarketLog.byteSize;
  }

  /**
   * Returns a readable version of {@link CreateMarketLog} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      market: this.market.toBase58(),
      creator: this.creator.toBase58(),
      baseMint: this.baseMint.toBase58(),
      quoteMint: this.quoteMint.toBase58(),
    };
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const createMarketLogBeet = new beet.BeetStruct<
  CreateMarketLog,
  CreateMarketLogArgs
>(
  [
    ['market', beetSolana.publicKey],
    ['creator', beetSolana.publicKey],
    ['baseMint', beetSolana.publicKey],
    ['quoteMint', beetSolana.publicKey],
  ],
  CreateMarketLog.fromArgs,
  'CreateMarketLog',
);
