/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js';
import * as beet from '@metaplex-foundation/beet';
import * as beetSolana from '@metaplex-foundation/beet-solana';

/**
 * Arguments used to create {@link ReferrerFeeLog}
 * @category Accounts
 * @category generated
 */
export type ReferrerFeeLogArgs = {
  market: web3.PublicKey;
  user: web3.PublicKey;
  mint: web3.PublicKey;
  referrerTokenAccount: web3.PublicKey;
  referrerFee: beet.bignum;
};
/**
 * Holds the data for the {@link ReferrerFeeLog} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class ReferrerFeeLog implements ReferrerFeeLogArgs {
  private constructor(
    readonly market: web3.PublicKey,
    readonly user: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly referrerTokenAccount: web3.PublicKey,
    readonly referrerFee: beet.bignum,
  ) {}

  /**
   * Creates a {@link ReferrerFeeLog} instance from the provided args.
   */
  static fromArgs(args: ReferrerFeeLogArgs) {
    return new ReferrerFeeLog(
      args.market,
      args.user,
      args.mint,
      args.referrerTokenAccount,
      args.referrerFee,
    );
  }

  /**
   * Deserializes the {@link ReferrerFeeLog} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [ReferrerFeeLog, number] {
    return ReferrerFeeLog.deserialize(accountInfo.data, offset);
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link ReferrerFeeLog} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<ReferrerFeeLog> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    );
    if (accountInfo == null) {
      throw new Error(`Unable to find ReferrerFeeLog account at ${address}`);
    }
    return ReferrerFeeLog.fromAccountInfo(accountInfo, 0)[0];
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UMnFStVeG1ecZFc2gc5K3vFy3sMpotq8C91mXBQDGwh',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, referrerFeeLogBeet);
  }

  /**
   * Deserializes the {@link ReferrerFeeLog} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [ReferrerFeeLog, number] {
    return referrerFeeLogBeet.deserialize(buf, offset);
  }

  /**
   * Serializes the {@link ReferrerFeeLog} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return referrerFeeLogBeet.serialize(this);
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link ReferrerFeeLog}
   */
  static get byteSize() {
    return referrerFeeLogBeet.byteSize;
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link ReferrerFeeLog} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      ReferrerFeeLog.byteSize,
      commitment,
    );
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link ReferrerFeeLog} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === ReferrerFeeLog.byteSize;
  }

  /**
   * Returns a readable version of {@link ReferrerFeeLog} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      market: this.market.toBase58(),
      user: this.user.toBase58(),
      mint: this.mint.toBase58(),
      referrerTokenAccount: this.referrerTokenAccount.toBase58(),
      referrerFee: (() => {
        const x = <{ toNumber: () => number }>this.referrerFee;
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber();
          } catch (_) {
            return x;
          }
        }
        return x;
      })(),
    };
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const referrerFeeLogBeet = new beet.BeetStruct<
  ReferrerFeeLog,
  ReferrerFeeLogArgs
>(
  [
    ['market', beetSolana.publicKey],
    ['user', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['referrerTokenAccount', beetSolana.publicKey],
    ['referrerFee', beet.u64],
  ],
  ReferrerFeeLog.fromArgs,
  'ReferrerFeeLog',
);
