/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';
import {
  GlobalCleanParams,
  globalCleanParamsBeet,
} from '../types/GlobalCleanParams';

/**
 * @category Instructions
 * @category GlobalClean
 * @category generated
 */
export type GlobalCleanInstructionArgs = {
  params: GlobalCleanParams;
};
/**
 * @category Instructions
 * @category GlobalClean
 * @category generated
 */
export const GlobalCleanStruct = new beet.BeetArgsStruct<
  GlobalCleanInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['params', globalCleanParamsBeet],
  ],
  'GlobalCleanInstructionArgs',
);
/**
 * Accounts required by the _GlobalClean_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] market
 * @property [_writable_] global
 * @category Instructions
 * @category GlobalClean
 * @category generated
 */
export type GlobalCleanInstructionAccounts = {
  payer: web3.PublicKey;
  market: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  global: web3.PublicKey;
};

export const globalCleanInstructionDiscriminator = 12;

/**
 * Creates a _GlobalClean_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category GlobalClean
 * @category generated
 */
export function createGlobalCleanInstruction(
  accounts: GlobalCleanInstructionAccounts,
  args: GlobalCleanInstructionArgs,
  programId = new web3.PublicKey('MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms'),
) {
  const [data] = GlobalCleanStruct.serialize({
    instructionDiscriminator: globalCleanInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.global,
      isWritable: true,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
