/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category GlobalClaimSeat
 * @category generated
 */
export const GlobalClaimSeatStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>([["instructionDiscriminator", beet.u8]], "GlobalClaimSeatInstructionArgs");
/**
 * Accounts required by the _GlobalClaimSeat_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] global
 * @property [_writable_] market
 * @category Instructions
 * @category GlobalClaimSeat
 * @category generated
 */
export type GlobalClaimSeatInstructionAccounts = {
  payer: web3.PublicKey;
  global: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  market: web3.PublicKey;
};

export const globalClaimSeatInstructionDiscriminator = 9;

/**
 * Creates a _GlobalClaimSeat_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category GlobalClaimSeat
 * @category generated
 */
export function createGlobalClaimSeatInstruction(
  accounts: GlobalClaimSeatInstructionAccounts,
  programId = new web3.PublicKey("MNFSTqtC93rEfYHB6hF82sKdZpUDFWkViLByLd1k1Ms"),
) {
  const [data] = GlobalClaimSeatStruct.serialize({
    instructionDiscriminator: globalClaimSeatInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.global,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
