/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token';
import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';
import {
  WrapperCancelOrderParams,
  wrapperCancelOrderParamsBeet,
} from '../types/WrapperCancelOrderParams';

/**
 * @category Instructions
 * @category CancelOrder
 * @category generated
 */
export type CancelOrderInstructionArgs = {
  params: WrapperCancelOrderParams;
};
/**
 * @category Instructions
 * @category CancelOrder
 * @category generated
 */
export const CancelOrderStruct = new beet.BeetArgsStruct<
  CancelOrderInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['params', wrapperCancelOrderParamsBeet],
  ],
  'CancelOrderInstructionArgs',
);
/**
 * Accounts required by the _CancelOrder_ instruction
 *
 * @property [_writable_] wrapperState
 * @property [**signer**] owner
 * @property [_writable_] traderTokenAccount
 * @property [_writable_] market
 * @property [_writable_] vault
 * @property [_writable_] mint
 * @property [] manifestProgram
 * @category Instructions
 * @category CancelOrder
 * @category generated
 */
export type CancelOrderInstructionAccounts = {
  wrapperState: web3.PublicKey;
  owner: web3.PublicKey;
  traderTokenAccount: web3.PublicKey;
  market: web3.PublicKey;
  vault: web3.PublicKey;
  mint: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  manifestProgram: web3.PublicKey;
};

export const cancelOrderInstructionDiscriminator = 4;

/**
 * Creates a _CancelOrder_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CancelOrder
 * @category generated
 */
export function createCancelOrderInstruction(
  accounts: CancelOrderInstructionAccounts,
  args: CancelOrderInstructionArgs,
  programId = new web3.PublicKey('UMnFStVeG1ecZFc2gc5K3vFy3sMpotq8C91mXBQDGwh'),
) {
  const [data] = CancelOrderStruct.serialize({
    instructionDiscriminator: cancelOrderInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.wrapperState,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.owner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.traderTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.market,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.mint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.manifestProgram,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
