name: Code Review - Debug UI

on:
  pull_request:
    branches: ['main']
    paths: [
      'client/ts/**',
      'client/idl/*.json',
      'debug-ui/**',
      'programs/**/instruction.rs',
      'yarn.lock'
    ]
  push:
    branches: ['main']
  workflow_dispatch:


jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./debug-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./debug-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

  depcheck:
    name: Dependency check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./debug-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Duplicates check
        run: npx yarn-deduplicate --list --fail

  test:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./debug-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Next build
        run: cp .env.example .env; yarn build
